version: 1
services:
  - type: web
    name: BotakMyHead
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: "composer install && php artisan key:generate"
    startCommand: "service nginx start && php-fpm"
    envVars:
      - key: APP_KEY
        value: base64:2XxLILgk1XOHSAP8YyDKBwrDh4X47x/ofbdTu48R6S0=
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: your-db-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: your-database-name
      - key: DB_USERNAME
        value: your-username
      - key: DB_PASSWORD
        value: your-password
